f
Kolobok37/java-filmorate pull request #1
Opened 2023-08-05 23:42 UTC by Kolobok37

2023-08-06 16:32 UTC, Yang-Pi requested changes

2023-08-06 16:32 UTC, Yang-Pi commented on .gitignore
> -*.class
Вот этот файл и остальные, относящиеся с CI программы, не нужно менять и удалять, поэтому верни их, пожалуйста.

2023-08-06 16:32 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +
Отступ лишний после аннотации

2023-08-06 16:32 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Film(int id, String name, String description, LocalDate releaseDate, Duration duration) {
Можешь использовать @AllArgsConstructor аннотацию из Lombok после @Data, тогда подобный конструктор будет создаваться автоматически

2023-08-06 16:32 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getName().isBlank()) {
Проверь поля объекта сначала на null, иначе легко получить NPE

2023-08-06 16:32 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            if (films.size() == 0) {
Подобный код нарушает принцип Single Responsibility (S из абривиатуры [SOLID](https://habr.com/ru/companies/ruvds/articles/426413/)), название метода - validationFilm, те установка id для объекта это максимально неочевидное действие, которое метод и не должен делать.

2023-08-06 16:32 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film createFilm(@RequestBody Film film) throws ValidationException {
Если дойти до основного родительского класса ValidationException, то мы увидим, что это RuntimeException, которое является Unchecked (непроверяемым), поэтому можно не писать явно, что метод может выкинуть это исключение

2023-08-06 16:32 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            if (users.size() == 0) {
Писал об этом для FilmController

2023-08-06 16:35 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getLogin().contains(" ")) {
А если будет 5 пробелов? поэтому используй метод isBlank

2023-08-06 16:35 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            user.setName(user.getLogin());
Тоже нарушение Single Responsibility принципа

2023-08-06 16:36 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            throw new ValidationException(HttpStatus.BAD_REQUEST, "Ошибка ввода данных пользователя");
При выбрасывании исключения нужно тоже писать лог, что произошло - log.error(...)

2023-08-06 19:08 UTC, Kolobok37 commented on .gitignore
> -*.class
+

2023-08-06 19:09 UTC, Kolobok37 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getLogin().contains(" ")) {
login проверяется методом isBlank

2023-08-06 19:11 UTC, Kolobok37 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            throw new ValidationException(HttpStatus.BAD_REQUEST, "Ошибка ввода данных пользователя");
в методе валидации логи указываются и если указать лог при выброске исключения, логи будут дублироваться, что будет мешать.

2023-08-07 16:33 UTC, Yang-Pi approved these changes

2023-08-07 16:50 UTC, merged